name: Correctness Check

on:
  push:
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install GCC 14
        run: |
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
          sudo apt-get update
          sudo apt-get install -y gcc-14 g++-14
          sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-14 100
          sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-14 100
        
      - name: Build partdiff
        run: make

      - name: Run small correctness check subset with valgrind
        uses: parcio/partdiff_tester/.github/actions/partdiff_tester@v0.1.1
        with:
          executable: "./partdiff"
          strictness: "4"
          valgrind: "true"
          shuffle: "42"
          max_num_tests: "5"

      - name: Run full correctness check without valgrind
        uses: parcio/partdiff_tester/.github/actions/partdiff_tester@v0.1.1
        with:
          executable: "./partdiff"
          strictness: "4"
          shuffle: "42"
